/**
 * <strong>Path Manager (TTT mock)</strong> — local stand-in for the European
 * Timetable Redesign / TTT path-allocation system.
 *
 * <p>{@link com.ordermgmt.railway.domain.pathmanager.model.PmReferenceTrain} is
 * derived from a FAHRPLAN
 * {@link com.ordermgmt.railway.domain.order.model.OrderPosition}; its lifecycle
 * runs through immutable
 * {@link com.ordermgmt.railway.domain.pathmanager.model.PmTrainVersion}s and a
 * static state machine in
 * {@link com.ordermgmt.railway.domain.pathmanager.service.PathProcessEngine} (NEW
 * → REQUESTED → DRAFT_OFFER → FINAL_OFFER → BOOKED, plus terminal CANCELED /
 * WITHDRAWN / NO_ALTERNATIVE / MODIFIED states).
 *
 * <p>Identifiers (TRID, PAID, PRID, ROID) are composite keys generated by
 * {@link com.ordermgmt.railway.domain.pathmanager.service.IdentifierGenerator}.
 *
 * <p>TTR-Phase-aware: which actions are valid in
 * {@link com.ordermgmt.railway.domain.pathmanager.service.PathProcessEngine}
 * depends on the current calendar position relative to the timetable year start
 * (ADR-013). For example, draft offers are not legal in Bestellphase 3.
 *
 * <p>Architecture: REST API as integration boundary, shared DB with {@code pm_*}
 * prefix, no microservice boundary (ADR-011). The "Mock leeren" button in the UI
 * uses {@link com.ordermgmt.railway.domain.pathmanager.service.PathManagerService}'s
 * admin-only reset for dev/test cycles.
 */
package com.ordermgmt.railway.domain.pathmanager;
