version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "kron12345"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "ci"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    labels:
      - "infrastructure"
